env:
  commonjs: true
  es6: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:jest/style
plugins:
  - jest
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  class-methods-use-this: 0
  func-names: 0
  implicit-arrow-linebreak: 0
  linebreak-style: [ 2, "unix" ]
  max-len: [ 2, { "code": 120 } ]
  no-param-reassign: 1
  no-plusplus: 0
  no-restricted-syntax: 1
  no-shadow: 0
  no-underscore-dangle: 0
  operator-linebreak: [ 1, "after", { "overrides": { "?": "before", ":": "before" } } ]
  max-classes-per-file: 0
  no-unused-vars: 1
  function-paren-newline: 0
  object-curly-newline: [ 2, { "consistent": true } ]
  'jest/no-disabled-tests': 0
