name: Publish Docker Agent Draft

on:
  push:
    branches:
      - deploy1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: tuan.nguyen@katalon.com
          password: Nht@@1234512345

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: AGENT_VERSION=7.0
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: htuan/testagent:7.0