
name: Publish Docker Agent
on:
  push:
    branches:
      - TES-5825

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: TES-5825

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: fijetso
          password: dckr_pat_O3RPDGL8tfT9FX29vzDzke-I1uE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: AGENT_VERSION=2.0.4
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: fijetso/katalon-agent:2.0.4