name: Publish Agent Docker
on:
  push:
    branches:
      - qtttt

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.A }}
          password: ${{ secrets.B }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'all'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          build-args: AGENT_VERSION=${{ inputs.version }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: drag0nfire19/katalon-agent:1.7.6