name: Publish Docker Agent 
on:
  push:
    branches:
      - v1.7.9

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v1.7.9

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.A }}
          password: ${{ secrets.B }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: AGENT_VERSION=1.7.9
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: drag0nfire19/katalon-agent:1.7.9
    
      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v2
      #   if: ${{ inputs.is-latest }}
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     build-args: AGENT_VERSION=${{ inputs.version }}
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: katalonstudio/agent:latest
