name: Publish Docker Agent Draft

on:
  push:
    branches:
      - test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: TES-5830

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: tuan.nguyen@katalon.com
          password: Nht@@1234512345

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: AGENT_VERSION=5.0
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: htuan/testagent:5.0
