name: Publish Docker Agent
on:
  push:
    branches:
      - ltest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ltest

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.A }}
          password: ${{ secrets.B }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/arm64
          file: ./Dockerfile
          build-args: AGENT_VERSION=2.0.3
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: lydoanndev/katalon-agent:2.0.3
