name: Publish Docker Agent 
on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: string
      is-latest:
        type: boolean
        description: latest
        required: false
  # push:
  #   branches:
  #     - asdasd
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: fb1

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: AGENT_VERSION=${{ inputs.version }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: katalonstudio/agent:${{ inputs.version }}
    
      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v5
      #   if: ${{ inputs.is-latest }}
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     build-args: AGENT_VERSION=${{ inputs.version }}
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: katalonstudio/agent:latest
