name: Publish Docker Agent 
on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: string
      is-latest:
        type: boolean
        description: latest
        required: false
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: AGENT_VERSION=${{ inputs.version }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: katalonstudio/agent:${{ inputs.version }}
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        if: ${{ inputs.is-latest }}
        with:
          context: ./
          file: ./Dockerfile
          build-args: AGENT_VERSION=${{ inputs.version }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: katalonstudio/agent:latest
