name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - release

concurrency:
  group: test-${{ github.head_ref ||  github.sha }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 20.9.0
    steps:

      - name: Checkout Katalon Agent
        uses: actions/checkout@v4
      
      - name: Install packages
        run: npm ci

      - name: Run test
        run: |
          npm run eslint
          npm run test:coverage || true
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage/lcov.info

      - name: Sonar Cloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        with:
          args: >
            -Dsonar.verbose=true
            -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run ESLint check
        uses: sibiraj-s/action-eslint@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          eslint-args: '-c .eslintrc.yml'
          extensions: 'js'
          annotations: true
