name: Demo Workflow Dispatch

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
